### ISSUE TITLE
Auto Home doesn't lower Z axis

### ISSUE THREAD

**Issue by jideriku** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#1]
I have bltouch, it's worked before on older firmware.

**Comment by pmjdebruijn** [comment]
Every firmware I publish is practically tested, so at least core functionality like G28/G29 has been verified to work in advance.

Did you care to read:
https://github.com/pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2/blob/master/README.md

Specifially:

**CRITICAL:** The BLTouch bed levelling sensor should be connected to the PROBE (and SERVO) headers, and triple check the actual pinouts before powering on the board.

**WARNING:** The Z-STOP header is ignored, as the BLTouch is effectively used as the Z axis endstop.

Presumably you have your BLTouch connected to Z-STOP.
