### ISSUE TITLE
PrusaSlicer settings

### ISSUE THREAD

**Issue by DaLukasDev** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#11]
Not really an Issue rather a request, could you maybe upload your PrusaSlicer settings somewhere.
I would love to have a look at them because I took over most of your settings stated in the readme. While it's working great for smaller prints but when I run longer prints I seem to have under extrusion problems and bad surface finishing which I didn't have in Cura and I can't seem to figure out why.
Cleaned nozzle and hot end, calibrated the extruder etc. didn't fix it so I'm thinking it's an Slicer issue but not 100% sure.

**Comment by pmjdebruijn** [comment]
I've commited most of my changes in PrusaSlicer to upstream, so 2.3 beta should work fairly well now. 

Keep in mind that bad surface finish is about as a generic problem description as possible. I'd suggest to try PrusaSlicer 2.3 beta, and post images if problem persist.
