### ISSUE TITLE
Could you add config files?

### ISSUE THREAD

**Issue by Atorcha** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#12]
First of all I have to thank you this firmware file, but, could you upload configuration.h and configuration_adv.h ?

Maybe in this way I can make some minor changes.

Thanks and regards.

**Comment by DaLukasDev** [comment]
Configuration files get pulled and modified by the .sh file.
You could edit these files after and recompile them yourself if u want.
