### ISSUE TITLE
Failed to compile firmware since last commit.

### ISSUE THREAD

**Issue by DaLukasDev** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#13]
Never had any issues compiling your firmware.
But now when I try to compile the firmware it errors out.
`Compiling .pio/build/STM32F103RC_btt_512K/src/src/HAL/STM32F1/watchdog.cpp.o
In file included from Marlin/src/HAL/STM32F1/dogm/../../../inc/../HAL/./STM32F1/HAL.h:36,                                                                                       
                 from Marlin/src/HAL/STM32F1/dogm/../../../inc/../HAL/HAL.h:26,         
                 from Marlin/src/HAL/STM32F1/dogm/../../../inc/MarlinConfig.h:30,       
                 from Marlin/src/HAL/STM32F1/dogm/u8g_com_stm32duino_fsmc.cpp:29:       
Marlin/src/HAL/STM32F1/dogm/../../../inc/../HAL/./STM32F1/fastio.h:30:10: fatal error: libmaple/gpio.h: No such file or directory                                               
   30 | #include <libmaple/gpio.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/STM32F103RC_btt_512K/src/src/HAL/STM32F1/dogm/u8g_com_stm32duino_fsmc.cpp.o] Error 1                                                                            
In file included from Marlin/src/HAL/STM32F1/../../inc/../HAL/./STM32F1/HAL.h:36,
                 from Marlin/src/HAL/STM32F1/../../inc/../HAL/HAL.h:26,                 
                 from Marlin/src/HAL/STM32F1/../../inc/MarlinConfig.h:30,               
                 from Marlin/src/HAL/STM32F1/onboard_sd.cpp:15:                         
Marlin/src/HAL/STM32F1/../../inc/../HAL/./STM32F1/fastio.h:30:10: fatal error: libmaple/gpio.h: No such file or directory                                                       
   30 | #include <libmaple/gpio.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/STM32F103RC_btt_512K/src/src/HAL/STM32F1/onboard_sd.cpp.o] Error 1`

Any idea why?

**Comment by pmjdebruijn** [comment]
A new STSTM32 library was released (7.0.0), which is incompatible, add this to my script:

sed -i 's;platform.*=.*ststm32$;platform          = ststm32@<7.0.0;' ${MARLIN_DIR}/platformio.ini

This has already been fixed in Marlin bugfix-2.0.x, and thus in the hopefully soon to be released 2.0.6
