### ISSUE TITLE
older bltouches

### ISSUE THREAD

**Issue by WalterWilson337** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#14]
can you make a copy but compatible with the older bltouches

thx

**Comment by pmjdebruijn** [comment]
I just publish what I use myself. So others can benefit from my work if it suits them.

If you need something different you're free to modify my script to suit your own needs, and build your own firmware.

**Comment by WalterWilson337** [comment]
can you change the probing speed down I don't know what you changed and you don't have the un compiled

**Comment by WalterWilson337** [comment]
I can't make my one I have tried and I can't downgrade to my former firmware because it's much too outdated

**Comment by pmjdebruijn** [comment]
> can you change the probing speed down I don't know what you changed and you don't have the un compiled

Again, the firmware does whatever I want it to do. I don't customize it for other people. If you want something different, that's something you'll need to work out yourself.

Given this is a git repository, you can trivially see, what I changed at any point in time, in the commit history:

https://github.com/pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2/commits/master

Specifically this:
https://github.com/pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2/commit/e0581bee3d079bd101b3f9ff956d012bbee333c3#diff-34a97950ad5ef517e78521c4a8d6799fR231

My build script skr_mini_e3_build.sh basically does everything it needs to build a firmware, including pulling in the relevant dependencies. It does however need to be run on a Linux host, but that's easy enough to install on a virtual machine if you're running Windows.

> I can't make my one I have tried and I can't downgrade to my former firmware because it's much too outdated

There a huge amount of information available online how to customize your own firmware, so given enough effort anybody can.

But, there's always the official reference firmwares from BigTreeTech themselves:
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V1.2  (I never tried those myself though)

And there's the option of buying a modern BLTouch if you simply don't want to deal with the hassle...

**Comment by WalterWilson337** [comment]
if you could do it for me I can pay

**Comment by WalterWilson337** [comment]
if any one makes the same config but but compatible with an older bltouch

**Comment by WalterWilson337** [comment]
I can pay

**Comment by pmjdebruijn** [comment]
Sorry, I'm not looking to take on commission work.

Maybe you can find a local makerspace, where someone might be able to help you out.
