### ISSUE TITLE
Can't build wheel for platformio

### ISSUE THREAD

**Issue by DaLukasDev** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#16]
When I run the bash script I get an error when building wheel for platformio.
[
![image](https://user-images.githubusercontent.com/36202721/95667117-de0c1880-0b61-11eb-9027-5a704143612b.png)
](url)
And I can't find the problem.
Thanks in advance

**Comment by pmjdebruijn** [comment]
Why do you presume it matters? That's just some python nonsense, the script should proceed to build a firmware.bin just fine.

If you're still not getting a proper firmware.bin, please post a full  build log, in proper text, and not a screenshot of a terminal with a particularly poor color scheme.

**Comment by pmjdebruijn** [comment]
This particular error message has been resolved in the latest version I just pushed.

**Comment by pmjdebruijn** [comment]
Given the reported issue was resolved, and lacking any new feedback, I'll be closing this issue.
