### ISSUE TITLE
PWM-controlled PIN need

### ISSUE THREAD

**Issue by trengtor** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#17]
It is necessary to make a backlight controlled via a pvm (g-code m355) with an external key. Is there a pin on the board connectors to which it will be possible to bind such a control?

![190452521_4409303619104260_822190006487658249_n](https://user-images.githubusercontent.com/16775489/119771062-c2256f00-bec5-11eb-96e9-516e80e51728.jpg)

![2021-02-16_16 30](https://user-images.githubusercontent.com/16775489/119771172-ee40f000-bec5-11eb-8b97-9f7552784ced.jpg)

![photo_2021-03-08_18-01-37](https://user-images.githubusercontent.com/16775489/119771205-fbf67580-bec5-11eb-9510-aeb0ff51fdec.jpg)

**Comment by pmjdebruijn** [comment]
I'm sharing the firmware exactly as I need it. It's not a community project.

You're free to modify my buildscript for your own purposes.
