### ISSUE TITLE
Marlin configuration files

### ISSUE THREAD

**Issue by migoo2** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#4]
Hello, thanks for the firmware, it works very fine.

I'm successfully using your firmware on the SKR Mini E3 V1.2 in a CR-10 with a 3DTouch.
Could you share the configuration files you used to generate this firmware.
I'd like to modify the bed parameters to use all the build volume of my CR10...

Regards, 

MiGoO

**Comment by pmjdebruijn** [comment]
I don't keep the config files around.

Just modify the build script which autogenerates the config files and subsequently the firmware itself.
