### ISSUE TITLE
ABL grid only does left front corner

### ISSUE THREAD

**Issue by runtpacket** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#5]
when G29 is issued the ABL probes the grid as expected. But, the grid size it is probing is only approx 30mm X 30mm. i.e. it only probes the front left section of the bed. I am going to try formatting SD and reapplying firmware. 

Formatted sd card. Reapplied firmware same result. rolled back to previous firmware I got from  you a couple weeks ago. 

Video https://www.dropbox.com/s/imeidqh9v62hl9d/VID_20200301_195708.mp4?dl=0

**Comment by pmjdebruijn** [comment]
Note in README.md:

X/Y Microstepping has been increased to 32 (resulting in 160 steps/mm).

Did you verify the X/Y steps/mm are set to 160 (given that they previously would have been 80).

Resetting the firmware to defaults will accomplish this as well. Do keep in mind to reconfigure your Z-Offset again after resetting.

**Comment by runtpacket** [comment]
That was it. Sorry my fault.
