### ISSUE TITLE
printing randomly out of bed

### ISSUE THREAD

**Issue by DaLukasDev** [pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2#8]
Another weird issue I've encountered is that sometimes when i start a print via octoprint, he starts the print fine heating up the bed and extruder etc.
But after the levelling part instead of going to the point he should be printing he starts printing mid air after the 9th probe. if I reset the printer and rerun the same file again from octoprint he prints perfectly fine.
This happend 3 times at random occasions. Any clue?

**Comment by pmjdebruijn** [comment]
No sorry, I've never used Octoprint... 

But if anything that's likely an upstream Marlin issue, or an upstream Octoprint issue....

BTW, are you using my start/stop gcodes as well?

**Comment by pmjdebruijn** [comment]
BTW, how high does it print "in the air"?

**Comment by DaLukasDev** [comment]
Was about to try your start and stop gcodes in my next print I slice. The height you get when probing the last point and then raising the z-axis as it does with all the probes. But instead of lowering and going to the x/y origin and drawing the priming line to clear the nozzle it just stays at that +-10 z and starts "printing". Yet it doesn't move it's head either it just spills out filament as it were printing.

**Comment by pmjdebruijn** [comment]
Did changing the start/end gcode change anything?

**Comment by DaLukasDev** [comment]
Just updated to latest commit and making new print with your start/stop gcode.
I'll keep u posted.

**Comment by DaLukasDev** [comment]
Closing this issue, after a few prints I can confirm that the start and stop gcode does a good job fixing these issue. Also this startcode is a lot better then the default cure startcode. Did switch over to prusaslicer which seems to be a lot better aswell!
